Attempt to add dns records multiple times if it fails
- this might be happening due to race condition when
  we open transaction
fixes:
```
+ gcloudcloud --project=cf-infra dns record-sets transaction add -z infrastructure --name terraforming-aws-pas.aws.infrastructure.cf-app.com --ttl 60 --type NS ns-1343.awsdns-39.org. ns-1998.awsdns-57.co.uk. ns-247.awsdns-30.com. ns-961.awsdns-56.net.
Record addition appended to transaction at [transaction.yaml].
+ gcloud --project=cf-infra dns record-sets transaction execute -z infrastructure
ERROR: (gcloud.dns.record-sets.transaction.execute) HTTPError 412: Precondition not met for 'entity.change.deletions[0]'
```

Co-authored-by: Christopher Hunter <hunter.christopher@icloud.com>